[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = [
    'find . -type d -name __pycache__ -exec rm -rf {} + || true',
    'find . -type f -name "*.pyc" -delete || true',
    'find . -type f -name "*.pyo" -delete || true',
    'pip install -r requirements.txt'
]

[start]
cmd = 'python worker.py'

[variables]
PYTHONDONTWRITEBYTECODE = '1'
PYTHONUNBUFFERED = '1'
